export const POST_ASSESSMENT = "POST_ASSESSMENT";
export const POST_ASSESSMENT_SUCCESS = "POST_ASSESSMENT_SUCCESS";
export const POST_ASSESSMENT_FAILURE = "POST_ASSESSMENT_FAILURE";

export const SET_ASSESSMENT_LOADING = "SET_ASSESSMENT_LOADING";