export const GET_USERS_BY_REFER = "GET_USERS_BY_REFER";
export const GET_USERS_BY_REFER_SUCCESS = "GGET_USERS_BY_REFER_SUCCESS";
export const GET_USERS_BY_REFER_FAILURE = "GGET_USERS_BY_REFER_FAILURE";

export const SET_CATEGORY_LOADING = "SET_CATEGORY_LOADING";