export const GET_USERS_BY_REFER = "GET_USERS_BY_REFER";
export const GET_USERS_BY_REFER_SUCCESS = "GET_USERS_BY_REFER_SUCCESS";
export const GET_USERS_BY_REFER_FAILURE = "GET_USERS_BY_REFER_FAILURE";

export const POST_USER = "POST_USER";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_FAILURE = "POST_USER_FAILURE";


export const SET_CATEGORY_LOADING = "SET_CATEGORY_LOADING";